/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Root': RouteRecordInfo<
      'Root',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '$Path': RouteRecordInfo<
      '$Path',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'Home': RouteRecordInfo<
      'Home',
      '/Home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PageDeepDeep': RouteRecordInfo<
      'PageDeepDeep',
      '/page/deep/deep',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PageDeepDeep2': RouteRecordInfo<
      'PageDeepDeep2',
      '/page/deep/deep2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PageDemoApi': RouteRecordInfo<
      'PageDemoApi',
      '/page/demo-api',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PageDemoIcons': RouteRecordInfo<
      'PageDemoIcons',
      '/page/demo-icons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.page.vue': {
      routes:
        | 'Root'
      views:
        | never
    }
    'src/pages/[...path].page.vue': {
      routes:
        | '$Path'
      views:
        | never
    }
    'src/pages/Home.page.vue': {
      routes:
        | 'Home'
      views:
        | never
    }
    'src/pages/page/deep/deep.page.vue': {
      routes:
        | 'PageDeepDeep'
      views:
        | never
    }
    'src/pages/page/deep/deep2.page.vue': {
      routes:
        | 'PageDeepDeep2'
      views:
        | never
    }
    'src/pages/page/demo-api.page.vue': {
      routes:
        | 'PageDemoApi'
      views:
        | never
    }
    'src/pages/page/demo-icons.page.vue': {
      routes:
        | 'PageDemoIcons'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
