/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Root': RouteRecordInfo<
      'Root',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '$Path': RouteRecordInfo<
      '$Path',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'Demos': RouteRecordInfo<
      'Demos',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DemosApiDemo': RouteRecordInfo<
      'DemosApiDemo',
      '/demos/api-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DemosCounterDemo': RouteRecordInfo<
      'DemosCounterDemo',
      '/demos/counter-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DemosCreate': RouteRecordInfo<
      'DemosCreate',
      '/demos/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DemosI18nDemo': RouteRecordInfo<
      'DemosI18nDemo',
      '/demos/i18n-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DemosNaiveUiDemo': RouteRecordInfo<
      'DemosNaiveUiDemo',
      '/demos/naive-ui-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DemosPrimevueDemo': RouteRecordInfo<
      'DemosPrimevueDemo',
      '/demos/primevue-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DemosWebsocketDemo': RouteRecordInfo<
      'DemosWebsocketDemo',
      '/demos/websocket-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Home': RouteRecordInfo<
      'Home',
      '/Home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Login': RouteRecordInfo<
      'Login',
      '/Login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.page.vue': {
      routes:
        | 'Root'
      views:
        | never
    }
    'src/pages/[...path].page.vue': {
      routes:
        | '$Path'
      views:
        | never
    }
    'src/pages/demos/index.page.vue': {
      routes:
        | 'Demos'
      views:
        | never
    }
    'src/pages/demos/api-demo.page.vue': {
      routes:
        | 'DemosApiDemo'
      views:
        | never
    }
    'src/pages/demos/counter-demo.page.vue': {
      routes:
        | 'DemosCounterDemo'
      views:
        | never
    }
    'src/pages/demos/create.page.vue': {
      routes:
        | 'DemosCreate'
      views:
        | never
    }
    'src/pages/demos/i18n-demo.page.vue': {
      routes:
        | 'DemosI18nDemo'
      views:
        | never
    }
    'src/pages/demos/naive-ui-demo/index.page.vue': {
      routes:
        | 'DemosNaiveUiDemo'
      views:
        | never
    }
    'src/pages/demos/primevue-demo.page.vue': {
      routes:
        | 'DemosPrimevueDemo'
      views:
        | never
    }
    'src/pages/demos/websocket-demo.page.vue': {
      routes:
        | 'DemosWebsocketDemo'
      views:
        | never
    }
    'src/pages/Home.page.vue': {
      routes:
        | 'Home'
      views:
        | never
    }
    'src/pages/Login.page.vue': {
      routes:
        | 'Login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
